### ISSUE TITLE
@directive wrong macro expansion

### ISSUE THREAD

**Issue by ypanke** [libocca/occa-transpiler#149]
```
#define MYSTR my_fn_

inline void my_fn_1() {}
inline void my_fn_2() {}


@directive("#define MYMACRO(idx) MYSTR ## idx")

@kernel void hello_kern() {
    for (int i = 0; i < 10; ++i; @outer) {
        for (int j = 0; j < 10; ++j; @inner) {


            MYMACRO(1)();
            MYMACRO(2)();

        }
    }
}
```

Original occa outputs:
```
inline void my_fn_1() {}

inline void my_fn_2() {}

extern "C" void hello_kern() {
#pragma omp parallel for
  for (int i = 0; i < 10; ++i) {
    for (int j = 0; j < 10; ++j) {
      my_fn_1();
      my_fn_2();
    }
  }
}
```

Current:
```
inline void my_fn_1() {}

inline void my_fn_2() {}

extern "C" void hello_kern() {
#pragma omp parallel for
  for (int i = 0; i < 10; ++i) {
    for (int j = 0; j < 10; ++j) {
      MYSTR1();
      MYSTR2();
    }
  }
```

**Comment by kchabSS** [comment]
Original OCCA does not follow C/C++ conventions and turns `MYMACRO(1)` into `my_fn_1` while GCC and CLang produce `MYSTR1`.

**Comment by IuriiKobein** [comment]
OCCA preprocessor expands macro not according to the spec. 
Clang and gcc do it identical.

**Comment by kchabSS** [comment]
This behavior is not connected with `@directive`, but with macro expansion and concatenation.
OCCA evaluates `MYSTR` while GCC and CLang follow the standard.

To achieve a proper result, we must use something like
`#define CONCAT(id1, id2) id1##id2` macro, and call it like this: `#define MYMACRO(idx) CONCAT(MYSTR, idx)`

This behavior is described in more detail here:
https://renenyffenegger.ch/notes/development/languages/C-C-plus-plus/preprocessor/macros/concatenate
https://renenyffenegger.ch/notes/development/languages/C-C-plus-plus/preprocessor/macros/token-paste-operator/index
