### ISSUE TITLE
Loop attribute in wrong place freezes transpiler

### ISSUE THREAD

**Issue by pavlo-hilei** [libocca/occa-transpiler#169]
The followint code: 
```C++
@kernel void hello_kern() {
    for (int i = 0; i < 10; @outer;++i) {
        @shared int shm[10];
        for (int j = 0; j < 10; ++j; @inner) {
            shm[j] = j;
        }
    }
}
```
Is freezing transpilator. 
Seems like it never exits loop in `isLooksLikeFunctionCall` @kchabSS you wrote that function, maybe you know what might be the problem

**Comment by IuriiKobein** [comment]
The halt is due to not taking into consideration scenario when the right parentheses is firstly.
In this case `i` is undeclare variable and there is   `)` right after
