### ISSUE TITLE
@shared and @exclusive handler must be called on variable declaration

### ISSUE THREAD

**Issue by pavlo-hilei** [libocca/occa-transpiler#213]
In the case of using @shared or @exclusive with typedef and then initializing the variable, the handler on this variable is not called. In such cases, diagnostics such as "Must be defined between [@outer] and [@inner]" are not checked.  

Additionally, OpenMP/Serial doesn't have a TypeDecl handler for @exclusive. Failing case:
```c++
typedef float ex_float32_t @exclusive;

@kernel void test_kernel() {
    @outer for (int i = 0; i < 32; ++i) {
        ex_float32_t c[32];
        @inner for (int j = 0; j < 32; ++j) {
            c[j] = i+j;
        }
    }
}
```

Similarly, DPCPP doesn't have a TypeDecl handler for @shared. Failing case:
```c++
typedef float sh_float32_t @shared;

@kernel void test_kernel() {
    @outer for (int i = 0; i < 32; ++i) {
        sh_float32_t b[32];
        @inner for (int j = 0; j < 32; ++j) {
            b[j] = i+j;
        }
    }
}
```

**Comment by kchabSS** [comment]
@pavlo-hilei Please check the Test files for the `Fix` PR.
