### ISSUE TITLE
Current release tar ball doesn't have submodules source code

### ISSUE THREAD

**Issue by thilinarmtb** [libocca/occa-transpiler#242]
When I look at the the source archive [here](https://github.com/libocca/occa-transpiler/releases/tag/v1.0) it doesn't contain the source for
the submodules. It would be great if you could make a new release with the
source code of submodules included. 

[This](https://github.com/AcademySoftwareFoundation/MaterialX/issues/317) issue has some scripts to do it using `git archive`.

**Comment by IuriiKobein** [comment]
Done

**Comment by thilinarmtb** [comment]
@IuriiKobein : I downloaded the v1.1 tar ball but it is still empty.

**Comment by thilinarmtb** [comment]
Oh, I see there are two different tar archives.

**Comment by thilinarmtb** [comment]
Neither of the tar files have the submodule source in them.

**Comment by IuriiKobein** [comment]
Hi @thilinarmtb 
Sorry, there was a bug in the git-archive-submodules.sh script.
The archive is tested and replaced.

**Comment by thilinarmtb** [comment]
I could build occa-transpiler with the latest archive.
